### PR TITLE
update alpaka to 0.4.0 dev 

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- update alpaka to up https://github.com/ComputationalRadiationPhysics/alpaka/commit/d5e59590f7649f09575a363d02582424b471aba6

```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="cupla@hzdr.de" git subtree pull --prefix alpaka git@github.com:ComputationalRadiationPhysics/alpaka.git develop --squash
```

- rename queue names
      - `Queue*Sync` to `Queue*Blocking`
      - `Queue*Async` to `Queue*NonBlocking`

- [x] rebase against #130

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
somehow the serial config header test failed during the execution.

```
g++ ../cupla/test/system/config/main.cpp ../cupla/test/system/config/kernel.cpp  -I../cupla/test/system/config/../../../include -I../cupla/test/system/config/../../../alpaka/include -std=c++11 -DCUPLA_ACC_CpuSerial -DCUPLA_HEADER_ONLY -o CpuSerial -I/trinity/shared/pkg/devel/boost/1.68.0/gcc/7.3.0/include -g

valgrind ./CpuSerial

==173080== Process terminating with default action of signal 6 (SIGABRT)
==173080==    at 0x5708207: raise (in /usr/lib64/libc-2.17.so)
==173080==    by 0x57098F7: abort (in /usr/lib64/libc-2.17.so)
==173080==    by 0x4EC7EA4: __gnu_cxx::__verbose_terminate_handler() (vterminate.cc:95)
==173080==    by 0x4EC5C95: __cxxabiv1::__terminate(void (*)()) (eh_terminate.cc:47)
==173080==    by 0x4EC5CE0: std::terminate() (eh_terminate.cc:57)
==173080==    by 0x4EC5F22: __cxa_throw (eh_throw.cc:93)
==173080==    by 0x4EF0B1D: std::__throw_system_error(int) (system_error.cc:81)
==173080==    by 0x405D5C: void std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (mutex:698)
==173080==    by 0x403CE5: std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (future:401)
==173080==    by 0x404331: std::promise<void>::set_value() (future:1313)
==173080==    by 0x4049CD: alpaka::queue::traits::Enqueue<alpaka::queue::cpu::detail::QueueCpuBlockingImpl, alpaka::event::EventCpu, void>::enqueue(alpaka::queue::cpu::detail::QueueCpuBlockingImpl&, alpaka::event::EventCpu&) (EventCpu.hpp:285)
==173080==    by 0x4064AB: void alpaka::queue::enqueue<alpaka::queue::cpu::detail::QueueCpuBlockingImpl, alpaka::event::EventCpu&>(alpaka::queue::cpu::detail::QueueCpuBlockingImpl&, alpaka::event::EventCpu&) (Traits.hpp:62)
==173080== 
```

**Comment by psychocoderHPC** [comment]
@BenjaminW3 could you have a look at this cupla example. Somehow it crashes only for the blocking queue during `set_value` for the `promise` but I do not know why.

**Comment by psychocoderHPC** [comment]
if futures are used we need  to link libpthread https://stackoverflow.com/questions/58489617/c-promise-set-value-fails-with-unknown-error-under-linux else we will see exactly the issue I got.

**Comment by BenjaminW3** [comment]
@psychocoderHPC should alpaka already add this dependency with some additional comment?

**Comment by psychocoderHPC** [comment]
I need to check if alpaka is adding pthread in any cases. In cupla it was triggered during the config header checks (standalone header without CMake).

**Comment by psychocoderHPC** [comment]
somehow it is still not working on the CI: https://travis-ci.org/ComputationalRadiationPhysics/cupla/jobs/601935613#L693

**Comment by psychocoderHPC** [comment]
> somehow it is still not working on the CI: https://travis-ci.org/ComputationalRadiationPhysics/cupla/jobs/601935613#L693

It was not working because we need  need to add the compiler flag `-pthread` and the linker flag `-lpthread`.
GCC help says:
```
-pthread
           Define additional macros required for using the POSIX threads library.  You should use this option consistently for both
           compilation and linking ...
```

**Comment by ax3l** [comment]
> if futures are used we need to link libpthread https://stackoverflow.com/questions/58489617/c-promise-set-value-fails-with-unknown-error-under-linux else we will see exactly the issue I got.

Just found another SO on the issue, since we are still discussing it in Alpaka:
https://stackoverflow.com/questions/48847236/stdasync-with-gcc-7-2-need-pthread-link-option

This links to the very non-standard, platform dependent docs on GCC Future and it's potential dependency on pthreads:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_concurrency.html

**Pull request merged**
