### PR TITLE
update travis CMake to 3.15.4

### PR DESCRIPTION
**Pull request by psychocoderHPC**
update travis cmake version

This update is required for #128 to switch to the latest alpaka dev branch

### CODE REVIEW

**Comment by ax3l** [comment]
But #128 uses CMake 3.11.4+, shouldn't that be the version you also want in CI?

**Comment by sbastrakov** [comment]
@ax3l this is a good point. I guess the idea was that [alpaka CI uses CMake 3.15.2](https://github.com/ComputationalRadiationPhysics/alpaka/pull/819) for some cofigurations.

**Comment by ax3l** [comment]
That seams itchy to me and I would update all requirements then. Explaining "all things but XY work with CMake 3.11.4 but some need 3.15.2+" to users is a communication nightmare.

Also: our CI should always (at least) test the oldest supported configuration, otherwise new features and silent dependency updates sneak in during development.

**Comment by sbastrakov** [comment]
@ax3l you are right, I did not understand that alpaka PR and so my explanation is wrong. @psychocoderHPC, I guess you know the reason for the change in this PR?

**Comment by psychocoderHPC** [comment]
@ax3l Yes makes sense to test the oldest supported CMake version. At the point of creating the PR I was only focused to get it running. 
We should update the CI again and go back to the minimal version and increase also in the cupla CMake scripts the min version to 3.11.4

**Pull request merged**
