### PR TITLE
Updates alpaka to 0.3.5.

### LINKED ISSUE #80: Compile error (outdated alpaka, misplaced LLAMA_NO_HOST_ACC_WARNING)
When using CUDA 10, there are also the warnings, but the error below occurs on CUDA 9.2.88 and CUDA 10.
It is the same bug as in [llama](https://github.com/ComputationalRadiationPhysics/llama/pull/17).
I try to fix it by updating it to the latest alpaka version, where it should be fixed.
Maybe it will take some time, but our students need cupla soon.

```
/opt/cuda/include/crt/math_functions.hpp:54:2: Warnung: #warning "crt/math_functions.hpp is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or c  uda_runtime.h instead." [-Wcpp]
   #warning "crt/math_functions.hpp is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
    ^~~~~~~
  In file included from /home/gcoe04/cuda-workspace/cupla/alpaka/include/alpaka/math/trunc/TruncCudaBuiltIn.hpp:38:0,
                   from /home/gcoe04/cuda-workspace/cupla/alpaka/include/alpaka/math/MathCudaBuiltIn.hpp:54,
                   from /home/gcoe04/cuda-workspace/cupla/alpaka/include/alpaka/acc/AccGpuCudaRt.hpp:38,
                   from /home/gcoe04/cuda-workspace/cupla/alpaka/include/alpaka/alpaka.hpp:40,
                   from /home/gcoe04/cuda-workspace/cupla/include/cupla_runtime.hpp:24,
                   from /home/gcoe04/cuda-workspace/cupla/src/stream.cpp:22:
  /opt/cuda/include/crt/math_functions.hpp:54:2: Warnung: #warning "crt/math_functions.hpp is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or c  uda_runtime.h instead." [-Wcpp]
   #warning "crt/math_functions.hpp is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
    ^~~~~~~
```
```
  /home/gcoe04/cuda-workspace/cupla/alpaka/include/alpaka/core/Assert.hpp(102): error: this pragma must immediately precede a declaration
  
  1 error detected in the compilation of "/tmp/tmpxft_0000275b_00000000-6_stream.cpp1.ii".
  CMake Error at matrixMul_generated_stream.cpp.o.cmake:279 (message):
    Error generating file
    /home/gcoe04/cuda-workspace/cupla/build/CMakeFiles/matrixMul.dir/__/__/__/src/./matrixMul_generated_stream.cpp.o
  
  
  make[2]: *** [CMakeFiles/matrixMul.dir/build.make:107: CMakeFiles/matrixMul.dir/__/__/__/src/matrixMul_generated_stream.cpp.o] Fehler 1
  make[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/matrixMul.dir/all] Fehler 2
  make: *** [Makefile:84: all] Fehler 2
```

### PR DESCRIPTION
**Pull request by tdd11235813**
Closes #80.

### CODE REVIEW

**Comment by ax3l** [comment]
uh dang, now I merged to master!

**Comment by ax3l** [comment]
I just fast-forwarded the same change to `dev` and reverted the change on `master`.

**Comment by tdd11235813** [comment]
Thanks, but I thought master is ok in this case, because the master is now dysfunctional again. 
So when it will be on the master? I use master+tag on my submodules. Why not committing onto master all the time and using (release) tags? Why there is a separate dev branch at all? Wouldn't be [trunk based development](https://trunkbaseddevelopment.com/) with only one long-lived branch more convenient? Maybe I already have asked this in the past w.r.t. alpaka, not sure at the moment, so we also can discuss it next week ;)

**Comment by ax3l** [comment]
Yep, we can do this. Just currently, most of our projects follow [a successful git branching model](https://nvie.com/posts/a-successful-git-branching-model/) since we did initially let our users interact with git source code directly and wanted to avoid giving them an "unstable" trunk/dev by default.

Nevertheless, I think with package managers and the overhead of `dev`/`master` we can certainly think about migrating to trunk-based devel as most projects nowadays do.

**Pull request merged**
