### PR TITLE
Make Cupla header-only

### PR DESCRIPTION
**Pull request by fwyzard**
Move the implementation of the Driver and of the API to the respective header files.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@fwyzard Thanks for the pull request. 
We discussed offline that we like to keep the possibility to have different cpp files (to support parallel builds) and like to have the possibility to use the code as header only project. We started for that the issue: https://github.com/ComputationalRadiationPhysics/cupla/issues/108

Your current suggestion has side effects on the compile time if cupla is used in a large project. 
I will keep this PR open and provide also a PR next week then we can discuss the dis/advantages of both implementations and side what we will merge.

**Comment by ax3l** [comment]
Just to clarify: we like the proposal and want to implement header-only vs. partly pre-compiled side-by-side, for the sake of compile time.

**Comment by psychocoderHPC** [comment]
@fwyzard Sry for the delay. I implemented the header only stand allows header in #112

**Comment by tdd11235813** [comment]
#112 is now merged into dev branch and should provide the wanted feature. I hope it is ok, when I close this for you in this case. Please let us know if there are issues or other things that should be added to cupla :)

**Comment by fwyzard** [comment]
Sure, and thanks for merging #112.

**Pull request closed without merging**
