### PR TITLE
alpaka 0.4.0-dev + intern renamings

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- update alpaka submodule to development branch for 0.4.X
- switch to new alpaka interface names
- increase cmake requirement to alpaka's required minimal version

- [x]  do not merge before #88 
- [x]  rebase against #93

### CODE REVIEW

**Comment by ax3l** [comment]
@psychocoderHPC ready for rebase :)

**Comment by psychocoderHPC** [comment]
CI must be updated because the used cmake version is to old:

https://travis-ci.org/ComputationalRadiationPhysics/cupla/jobs/483344289#L745-L753

**Comment by ax3l** [comment]
prepared in #92

**Comment by psychocoderHPC** [comment]
alapka 0.4.X requires clang 4+ https://travis-ci.org/ComputationalRadiationPhysics/cupla/jobs/483795311#L740-L741 therefor this PR is not passing the CI

**Comment by psychocoderHPC** [comment]
PR with update to clang 4.0 #93

**Comment by ax3l** [comment]
@psychocoderHPC ready for rebase (in case CUDA 7.5 is still supported)

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC ready for rebase (in case CUDA 7.5 is still supported)

Ohh no it is not supported anymore. I will prepare yet another PR to increase the cuda version.

**Comment by ax3l** [comment]
No prob, that's easy with the scripts we have in place :)

**Comment by ax3l** [comment]
Ready for rebase, again :)

**Comment by psychocoderHPC** [comment]
@ax3l Shutdown you browser you said you make a vacation.

**Comment by ax3l** [comment]
(Last thing: don't forget to update your docs, readme should read cmake 3.11+ now). Over & out

**Pull request merged**
